# fly.toml app configuration file generated for haxmail on 2025-03-08T23:11:55+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haxmail'
primary_region = 'ams'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 2525
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2525

  [[services.ports]]
    port = 25

  [[services.ports]]
    port = 465

  [[services.ports]]
    port = 587
    handlers = ['tls']

  [[services.ports]]
    port = 2525
    handlers = ['tls']

[[vm]]
  size = 'shared-cpu-1x'
